set names utf8;
use shiki;


create table if not exists credit_code_list(
	credit_code varchar(255),
	credit_name varchar(255)
);


select sleep(1) from dual;
insert into credit_code_list values("000069", "atre CARD");
insert into credit_code_list values("001530", "京王パスポートカード");
insert into credit_code_list values("012901", "VIEW");
insert into credit_code_list values("012969", "GRANDUO ポイントカード");
insert into credit_code_list values("100100", "ソニーファイナンスインターナショナル Edy");
insert into credit_code_list values("100190", "AMC 宮交バスカ Edy");
insert into credit_code_list values("100196", "ANA MILEAGE CLUB Edy");
insert into credit_code_list values("100500", "三井住友カード Edy");
insert into credit_code_list values("120611", "楽天銀行 スーパーローンカード");
insert into credit_code_list values("127698", "三井住友");
insert into credit_code_list values("127698", "三井住友カード");
insert into credit_code_list values("127698", "三井住友カード");
insert into credit_code_list values("200000", "イズミヤカード（プロパー）");
insert into credit_code_list values("200100", "マックチップ(三井住友銀行) Edy");
insert into credit_code_list values("210191", "D-ONEカード(第一専門店会)");
insert into credit_code_list values("300100", "GAITAME.com(ビットワレット) Edy");
insert into credit_code_list values("300140", "お財布携帯(F) Edy");
insert into credit_code_list values("300150", "お財布携帯(SO) Edy");
insert into credit_code_list values("300300", "BIG ECHO MEMBERS CARD Edy");
insert into credit_code_list values("307000", "OMCハウス");
select sleep(1) from dual;
insert into credit_code_list values("310000", "JCB昭和シェルビジネスカード");
insert into credit_code_list values("334021", "ペルソナハウス");
insert into credit_code_list values("352824", "郵貯カード《セゾン》-JCB");
insert into credit_code_list values("352830", "ロフト《セゾン》VISA");
insert into credit_code_list values("352840", "JAF《セゾン》JCB");
insert into credit_code_list values("352840", "MONEY KitセゾンJCB");
insert into credit_code_list values("352855", "《セゾン》JCBカード");
insert into credit_code_list values("352859", "出光カードmydoplus JCB");
insert into credit_code_list values("352865", "JAF《セゾン》JCB");
insert into credit_code_list values("352865", "MUJI SAISON JCB");
insert into credit_code_list values("352867", "Ｍｅｉセゾン JCB");
insert into credit_code_list values("352868", "PEC SAISON JCB");
insert into credit_code_list values("352873", "MMC SAISON JCB");
insert into credit_code_list values("354002", "さくらカード 一般");
insert into credit_code_list values("354006", "JCB　福岡カード");
insert into credit_code_list values("354008", "JCB");
insert into credit_code_list values("354009", "UFJ JCB SNOOPY-L");
insert into credit_code_list values("354012", "UFJ JCB");
insert into credit_code_list values("354014", "JCB北海道・JCBカード");
insert into credit_code_list values("354016", "セーブオン JCB");
select sleep(1) from dual;
insert into credit_code_list values("354017", "りそなJCB");
insert into credit_code_list values("354019", "UFJ JCB");
insert into credit_code_list values("354019", "さくらカードJCB");
insert into credit_code_list values("354020", "JAF JCB");
insert into credit_code_list values("354020", "JCB NET PLUS");
insert into credit_code_list values("354020", "PIA JCB");
insert into credit_code_list values("354021", "スルガ銀行JCB");
insert into credit_code_list values("354022", "MJC-JCB");
insert into credit_code_list values("354022", "トライカードJCB");
insert into credit_code_list values("354023", "ANA-SFC-JCB");
insert into credit_code_list values("354023", "JCB-LINDA");
insert into credit_code_list values("354023", "JCBコーポレート一般");
insert into credit_code_list values("354023", "ＪＲJCBビジネスプラスカード");
insert into credit_code_list values("354023", "フィナンシャルワンメンバーズUFJ-JCB(グランデ)");
insert into credit_code_list values("354023", "フィナンシャルワンメンバーズUFJ-JCB(一般)");
insert into credit_code_list values("354023", "早稲田カードJCB");
insert into credit_code_list values("354024", "ANA-JCB 一般");
insert into credit_code_list values("354024", "FinacJCB");
insert into credit_code_list values("354024", "FinancialOne-JCB");
insert into credit_code_list values("354024", "JCB");
select sleep(1) from dual;
insert into credit_code_list values("354024", "JCB");
insert into credit_code_list values("354024", "JCB ANA WIDE");
insert into credit_code_list values("354024", "JCB JCB");
insert into credit_code_list values("354024", "慶應JCB");
insert into credit_code_list values("354025", "ANA JCB一般");
insert into credit_code_list values("354025", "JCB XｰTimes");
insert into credit_code_list values("354025", "JCB マクドナルド");
insert into credit_code_list values("354025", "JCB-Arubara");
insert into credit_code_list values("354025", "U-29/JCBカード");
insert into credit_code_list values("354025", "さくらグランデ");
insert into credit_code_list values("354026", "ANA-JCB 一般");
insert into credit_code_list values("354026", "JCB-グランデ");
insert into credit_code_list values("354026", "JCBコーポレート一般");
insert into credit_code_list values("354026", "MJC-JCB");
insert into credit_code_list values("354026", "ORIX Rent-A-Car Card JCB");
insert into credit_code_list values("354026", "U-29カード/JCB");
insert into credit_code_list values("354026", "UFJ-JCB");
insert into credit_code_list values("354026", "株式会社ジェーシービー/MJC");
insert into credit_code_list values("354027", "ANA-JCB 一般");
insert into credit_code_list values("354027", "ANA-JCB-WIDE");
select sleep(1) from dual;
insert into credit_code_list values("354027", "JCB Arubara");
insert into credit_code_list values("354027", "JCB E.GO");
insert into credit_code_list values("354027", "JCB LivingPlus");
insert into credit_code_list values("354027", "JCB U-29");
insert into credit_code_list values("354027", "JCB-NetMile-Arubara");
insert into credit_code_list values("354027", "フィナンシャルワンメンバーズUFJ-JCB(一般)");
insert into credit_code_list values("354027", "早稲田カード");
insert into credit_code_list values("354027", "明治大学学生カード JCB");
insert into credit_code_list values("354028", "さくらJCB-Arubara");
insert into credit_code_list values("354028", "さくらカード");
insert into credit_code_list values("354028", "フィナンシャルワンメンバーズUFJ-JCB(グランデ)");
insert into credit_code_list values("354028", "株式会社JCB-UnitedAirline");
insert into credit_code_list values("354029", "ANA-JCB 一般");
insert into credit_code_list values("354029", "JCB E.GO");
insert into credit_code_list values("354029", "JCB Living Plus");
insert into credit_code_list values("354029", "JCB Type Select");
insert into credit_code_list values("354029", "JCB Viaggio");
insert into credit_code_list values("354029", "バイオハザード JCBカード");
insert into credit_code_list values("354029", "明治大学JCBカード");
insert into credit_code_list values("354030", "ANA-JCB 一般");
select sleep(1) from dual;
insert into credit_code_list values("354030", "JCB J-1CARD");
insert into credit_code_list values("354030", "UFJ-JCB");
insert into credit_code_list values("354031", "ANA-JCB 一般");
insert into credit_code_list values("354060", "大学生協-JCB");
insert into credit_code_list values("354062", "JCB-ANA-St");
insert into credit_code_list values("354068", "JCB");
insert into credit_code_list values("354068", "Microsoft Plus三和JCB");
insert into credit_code_list values("354069", "JAL Card-CLUB-A-JCB");
insert into credit_code_list values("354069", "JAL Card-JCB");
insert into credit_code_list values("354069", "JAL-JCB");
insert into credit_code_list values("354069", "JALカードnavi JCB");
insert into credit_code_list values("354070", "JCBぴあカード");
insert into credit_code_list values("354070", "JCBセリーグ阪神タイガースカード");
insert into credit_code_list values("354072", "JCB DRIVER'S PLUS/ETC");
insert into credit_code_list values("354074", "新銀行東京カード JCB");
insert into credit_code_list values("354077", "JCBネクサス");
insert into credit_code_list values("354077", "フィナンシャルワンメンバーズUFJ-JCB(ネクサス)");
insert into credit_code_list values("354080", "JCBシナジー");
insert into credit_code_list values("354080", "シナジー");
insert into credit_code_list values("354082", "JCB北海道・グランデ");
select sleep(1) from dual;
insert into credit_code_list values("354083", "ANA　JCB　郵貯");
insert into credit_code_list values("354087", "DoCoMo JCB");
insert into credit_code_list values("354087", "DoCoMo UFJ-JCB");
insert into credit_code_list values("354088", "Persona JCB");
insert into credit_code_list values("354089", "小田急-JCB");
insert into credit_code_list values("354090", "アイワイカードーJCB");
insert into credit_code_list values("354092", "アイワイカード　JCB");
insert into credit_code_list values("354093", "アイワイカード - JCB");
insert into credit_code_list values("354100", "JCB");
insert into credit_code_list values("354100", "JCB　Gold");
insert into credit_code_list values("354100", "西銀JCB-G");
insert into credit_code_list values("354101", "ANA-JCB-wide GOLD");
insert into credit_code_list values("354101", "JCB");
insert into credit_code_list values("354101", "JCB");
insert into credit_code_list values("354101", "JCB GOLD");
insert into credit_code_list values("354101", "JCB GOLD プロパー");
insert into credit_code_list values("354101", "JCB Gold ANA");
insert into credit_code_list values("354101", "JCB Gold ANA SFC");
insert into credit_code_list values("354101", "JCBＧＯＬＤ　ＵＮＩＴＥＤマイレージプラス★");
insert into credit_code_list values("354101", "慶應JCB-Gold");
select sleep(1) from dual;
insert into credit_code_list values("354101", "早稲田ＧＯＬＤカード");
insert into credit_code_list values("354102", "JCB");
insert into credit_code_list values("354102", "JCBゴールド");
insert into credit_code_list values("354102", "フィナンシャルワンメンバーズUFJ-JCB(ゴールド)");
insert into credit_code_list values("354169", "JAL Card-CLUB-A-JCB-G");
insert into credit_code_list values("354180", "JCB THE CLASS");
insert into credit_code_list values("354181", "JCB Business(私学メンバーズカード)");
insert into credit_code_list values("354181", "JCB-Business");
insert into credit_code_list values("354181", "JR-JCB-BUSINESS-Gold");
insert into credit_code_list values("354255", "Pastown JCB");
insert into credit_code_list values("354269", "J-WESTエクスプレスJCB");
insert into credit_code_list values("354287", "HANA PLUS JCBカード");
insert into credit_code_list values("354290", "小田急ポイントクレジットカード");
insert into credit_code_list values("355100", "JCB法人ゴールド");
insert into credit_code_list values("358010", "日立カード　一般");
insert into credit_code_list values("358014", "NOVA CARD JCB(日立カードサービス)");
insert into credit_code_list values("358201", "日専連おびひろJCB");
insert into credit_code_list values("358204", "日専連JCB");
insert into credit_code_list values("358273", "dsp JCB");
insert into credit_code_list values("358277", "APLUS JCB");
select sleep(1) from dual;
insert into credit_code_list values("358277", "TSUTAYA-APULS-JCB");
insert into credit_code_list values("358277", "TSUTAYA　APLUS　JCB");
insert into credit_code_list values("358277", "なんばCITY-APLUS-JCB");
insert into credit_code_list values("358290", "GE-JCB");
insert into credit_code_list values("358292", "GE JCB (GC)");
insert into credit_code_list values("358298", "GE JCB(GAGA)");
insert into credit_code_list values("358298", "GE-JCB (シャア専用カード)");
insert into credit_code_list values("358299", "GE Money Classic JCB");
insert into credit_code_list values("358299", "GE Money Gold JCB");
insert into credit_code_list values("358305", "＠ｎｉｆｔｙ Orico-JCB");
insert into credit_code_list values("358305", "システムソフト ORICO JCB");
insert into credit_code_list values("358305", "ミニミニ Orico-JCB");
insert into credit_code_list values("358305", "モンテローザOrico-JCB");
insert into credit_code_list values("358403", "楽天カードJCB");
insert into credit_code_list values("358410", "AEON-JCB");
insert into credit_code_list values("358411", "AEON-JCB");
insert into credit_code_list values("358413", "AEON-JCB");
insert into credit_code_list values("358413", "イオン");
insert into credit_code_list values("358419", "AEON JCB/ETC");
insert into credit_code_list values("358419", "AEON-スポーツオーソリティー-JCB");
select sleep(1) from dual;
insert into credit_code_list values("358419", "イオンJCB");
insert into credit_code_list values("358481", "Panasonic-JCB");
insert into credit_code_list values("358488", "Panasonic-JCB");
insert into credit_code_list values("358490", "高島屋JCB");
insert into credit_code_list values("358501", "TOBU(東武) JCB");
insert into credit_code_list values("358702", "北専JCB");
insert into credit_code_list values("358703", "札信販JCB");
insert into credit_code_list values("358708", "GE Money GOLD");
insert into credit_code_list values("358711", "JACCS JCB (偽造対策のため3587-14に移行)");
insert into credit_code_list values("358711", "JACCS-JCB ピーシーデポカード");
insert into credit_code_list values("358713", "ミドリ JACCS JCB");
insert into credit_code_list values("358714", "JACCS JCB");
insert into credit_code_list values("358714", "１００満ボルト　ジャックス　JCB");
insert into credit_code_list values("358741", "JUPI");
insert into credit_code_list values("358741", "JUPI Card");
insert into credit_code_list values("358741", "ファミマ");
insert into credit_code_list values("358742", "UCS");
insert into credit_code_list values("358742", "UCS-JCB-G");
insert into credit_code_list values("358742", "UCS-JCBカード(一般)ユニークレジットサービス");
insert into credit_code_list values("358743", "全日信販JCB");
select sleep(1) from dual;
insert into credit_code_list values("358744", "ゆめJCB");
insert into credit_code_list values("358746", "OSAKA PiTaPa-トヨタTS3-JCB");
insert into credit_code_list values("358746", "ＪＫＪＫ");
insert into credit_code_list values("358747", "トヨタTS3カード JCB-G");
insert into credit_code_list values("358750", "OMC JCB");
insert into credit_code_list values("358751", "OMC JCB");
insert into credit_code_list values("358751", "ゆうちょ OMC JCB");
insert into credit_code_list values("358759", "OMC JCBゴールド");
insert into credit_code_list values("358761", "ファミマTカード");
insert into credit_code_list values("358781", "CF JCB");
insert into credit_code_list values("358781", "IDEX");
insert into credit_code_list values("358781", "ジェイアール東海エクスプレスカード　ジェーシービー　セントラルファイナンス発行");
insert into credit_code_list values("358787", "BIC VIeW JCB");
insert into credit_code_list values("358787", "JAL-VIEW-JCB CLUB-A(");
insert into credit_code_list values("358787", "JAL-VIEW-JCB CLUB-A(JALグローバルクラブ）");
insert into credit_code_list values("358787", "JALCard Suica JCB");
insert into credit_code_list values("358787", "JALカードSuica View JCB");
insert into credit_code_list values("358787", "VIEW BIC Suica JCB");
insert into credit_code_list values("358787", "View-Suica-JCB");
insert into credit_code_list values("358787", "ＶＩＥＷ　ビックカメラ　JCB");
select sleep(1) from dual;
insert into credit_code_list values("358793", "イズミヤカード-JCB");
insert into credit_code_list values("358796", "P-one金 JCB");
insert into credit_code_list values("358821", "荘内銀行バンクカード-JCB");
insert into credit_code_list values("358874", "bc");
insert into credit_code_list values("364888", "平茄子（タイ）");
insert into credit_code_list values("366301", "Times Club Card(ポイントカード)");
insert into credit_code_list values("369115", "Diners-Black");
insert into credit_code_list values("369115", "WASEDA Diners");
insert into credit_code_list values("369116", "ANA Diners");
insert into credit_code_list values("369116", "ダイナース　（平・提携）");
insert into credit_code_list values("369116", "ダイナース（提携JC）");
insert into credit_code_list values("369116", "ダイナースプレミアム");
insert into credit_code_list values("369150", "DINERS NewOtaniClub");
insert into credit_code_list values("369161", "JAL Diners");
insert into credit_code_list values("369519", "Diners 平");
insert into credit_code_list values("369536", "ダイナース");
insert into credit_code_list values("369541", "平茄子");
insert into credit_code_list values("369554", "Diners (平茄子）");
insert into credit_code_list values("369563", "Diners コーポレート");
insert into credit_code_list values("369564", "Diners (平茄子）");
select sleep(1) from dual;
insert into credit_code_list values("369570", "Diners Club (平茄子）");
insert into credit_code_list values("369570", "ダイナース　プロパー");
insert into credit_code_list values("369571", "Diners proper");
insert into credit_code_list values("369571", "ダイナース　平");
insert into credit_code_list values("369591", "ダイナース・平");
insert into credit_code_list values("371288", "アメックス・ブルー（学生カード）　アメリカ発行");
insert into credit_code_list values("376101", "AMERICAN EXPRESS(GOLD)");
insert into credit_code_list values("376103", "AMEX GOLD");
insert into credit_code_list values("376104", "アメックス");
insert into credit_code_list values("376105", "アメックス　グリーン");
insert into credit_code_list values("376106", "雨金");
insert into credit_code_list values("376107", "雨金");
insert into credit_code_list values("376108", "AMERICAN EXPRESS (GOLD)");
insert into credit_code_list values("376112", "AMEX");
insert into credit_code_list values("376118", "AMEX GREEN");
insert into credit_code_list values("376119", "アメリカン・エキスプレス・プラチナ");
insert into credit_code_list values("376121", "AMEX プラチナ");
insert into credit_code_list values("376121", "AMEX 緑");
insert into credit_code_list values("376122", "オークラクラブAMEX");
insert into credit_code_list values("376124", "AMEX-Green");
select sleep(1) from dual;
insert into credit_code_list values("376126", "アメリカン・エキスプレス");
insert into credit_code_list values("376127", "アメックス緑");
insert into credit_code_list values("376127", "アメックス緑");
insert into credit_code_list values("376128", "amex");
insert into credit_code_list values("376128", "雨白金");
insert into credit_code_list values("376128", "新生アメックス緑");
insert into credit_code_list values("376129", "Amex (green)");
insert into credit_code_list values("376129", "Amex platinum");
insert into credit_code_list values("376129", "新生アメックス緑");
insert into credit_code_list values("376131", "雨金");
insert into credit_code_list values("376132", "Amex-Platinum");
insert into credit_code_list values("376132", "アメックス");
insert into credit_code_list values("376133", "アメ金");
insert into credit_code_list values("376150", "雨緑コーポレイト");
insert into credit_code_list values("376153", "雨緑コーポレイト");
insert into credit_code_list values("376168", "雨緑 コーポレート");
insert into credit_code_list values("376170", "AMEX-BUSINESS-GOLD");
insert into credit_code_list values("376171", "雨金コーポレート");
insert into credit_code_list values("376176", "雨金コーポレート");
insert into credit_code_list values("376177", "AMEX Centurion Card");
select sleep(1) from dual;
insert into credit_code_list values("376177", "AMEX　ｐｔ");
insert into credit_code_list values("376178", "アメックス　センチュリオン");
insert into credit_code_list values("376310", "雨金（タイ）");
insert into credit_code_list values("376511", "AMEX コンパニオン");
insert into credit_code_list values("376512", "AMEX コンパニオン（色がグレー）");
insert into credit_code_list values("377781", "JAF《セゾン》AMEX");
insert into credit_code_list values("377781", "SAISON-AMEX");
insert into credit_code_list values("377781", "Saison Platinum AMEX");
insert into credit_code_list values("377781", "mizuhoマイレージクラブカードアメリカンエキスプレスベーシック");
insert into credit_code_list values("377781", "《セゾン》アメリカンエキスプレスカード");
insert into credit_code_list values("377781", "セゾン");
insert into credit_code_list values("377781", "鶴見はなぽーとブロッサムSAISON雨");
insert into credit_code_list values("377782", "DoCoMo《セゾン》・アメリカン・エキスプレス");
insert into credit_code_list values("377782", "セゾン　AMEX");
insert into credit_code_list values("377856", "GE Money 
 Express");
insert into credit_code_list values("377858", "MUFGカード Gold American Express");
insert into credit_code_list values("379029", "American Express GIFT CARD (アメックス・プリペイドカード(有))");
insert into credit_code_list values("400367", "ANA CARD U.S.A.");
insert into credit_code_list values("402855", "CITIBANK Dollar VISA");
insert into credit_code_list values("406042", "BANK ONE - THE ONE Card (VISA check card)");
select sleep(1) from dual;
insert into credit_code_list values("415314", "トヨタファイナンス");
insert into credit_code_list values("415314", "日興プラチナデビットカード");
insert into credit_code_list values("420510", "イオンゴールドカード");
insert into credit_code_list values("420519", "AEON VISA ゴールド");
insert into credit_code_list values("420520", "AEON-VISA");
insert into credit_code_list values("420523", "AEON-VISA");
insert into credit_code_list values("420529", "AEON-VISA");
insert into credit_code_list values("420529", "VISA");
insert into credit_code_list values("421614", "スルガVISAデビット");
insert into credit_code_list values("421615", "スルガVISAデビ　ダイレクトバンク支店");
insert into credit_code_list values("421641", "スルガ　デビット");
insert into credit_code_list values("422002", "ライフVISAカード");
insert into credit_code_list values("425955", "Banco BANTEC");
insert into credit_code_list values("429769", "楽天VISA");
insert into credit_code_list values("429769", "楽天カード（楽天KC） VISA");
insert into credit_code_list values("429770", "楽天プレミアム　VISA");
insert into credit_code_list values("431126", "三井住友インターナショナルキャッシュカード");
insert into credit_code_list values("432371", "Wells Fargo Bank");
insert into credit_code_list values("438235", "新生銀行インターナショナルキャッシュカード");
insert into credit_code_list values("438400", "Banco BANTEC");
select sleep(1) from dual;
insert into credit_code_list values("439101", "東京三菱銀行　国際キャッシュカード");
insert into credit_code_list values("439102", "東京三菱キャッシュカード<インターナショナル>");
insert into credit_code_list values("448775", "United Bank Check Card (VISA DebitかつCirrus/STAR)");
insert into credit_code_list values("452581", "JACCS-VISAカード");
insert into credit_code_list values("452581", "ジャックスカードVISA");
insert into credit_code_list values("452583", "トステムビバ倶楽部JACCS-VISA");
insert into credit_code_list values("452584", "JACCS VISA(TSUTAYA提携から切り替え)");
insert into credit_code_list values("452584", "ルネッサンスＶＩＳＡかーど");
insert into credit_code_list values("452590", "AEON-VISA");
insert into credit_code_list values("453138", "横浜銀行バンクカード(BC)-VISA");
insert into credit_code_list values("453177", "福岡銀行-Bank Card-VISA");
insert into credit_code_list values("453400", "DCカード GOLD");
insert into credit_code_list values("453412", "DCプロパーVISA（BTM引落）");
insert into credit_code_list values("453418", "京急-DC-VISA");
insert into credit_code_list values("453419", "DC-VISA");
insert into credit_code_list values("453422", "早稲田・DC-VISA　");
insert into credit_code_list values("453426", "JAF DC");
insert into credit_code_list values("453429", "日専連DC-VISA");
insert into credit_code_list values("453436", "JAL");
insert into credit_code_list values("453436", "JAL-DC-VISA");
select sleep(1) from dual;
insert into credit_code_list values("453438", "DC-ジザイル");
insert into credit_code_list values("453439", "DC MSNカード");
insert into credit_code_list values("453440", "DC VISA corporate");
insert into credit_code_list values("453442", "JAL-DC-VISA（ゴールド）");
insert into credit_code_list values("453450", "123");
insert into credit_code_list values("453450", "DC GOLD VISA");
insert into credit_code_list values("453450", "DC-G-VISA");
insert into credit_code_list values("453450", "DC-GOLD VISA 盲導犬協会");
insert into credit_code_list values("453450", "DCプロパー-VISA-Gold-VINGT（BTM引落");
insert into credit_code_list values("453450", "JAL CLUB-A GOLD DC-VISA");
insert into credit_code_list values("453452", "DC/財団法人日本盲導犬協会カード（一般）");
insert into credit_code_list values("453452", "NetMile DC-VISA");
insert into credit_code_list values("453460", "あしぎんDC VISA Gold");
insert into credit_code_list values("453468", "DC");
insert into credit_code_list values("453478", "ひろぎんDCカード");
insert into credit_code_list values("453486", "第四銀行-DC-VISA 一般");
insert into credit_code_list values("453490", "地銀ＤＣビジネスゴールド");
insert into credit_code_list values("453851", "NICOS プレミオ VISA");
insert into credit_code_list values("453851", "NICOS-VISA Gold");
insert into credit_code_list values("453851", "NICOS-VISA-Gブロパー");
select sleep(1) from dual;
insert into credit_code_list values("453852", "NICOS VISA GOLD");
insert into credit_code_list values("453862", "ＮＩＣＯＳ　ＰＡＲＴＮＥＲ　ゴールドカード");
insert into credit_code_list values("453865", "Drivers EDGE/NICOS-VISA");
insert into credit_code_list values("453865", "EDGE ON NICOS CARD VISA");
insert into credit_code_list values("453865", "ENEOSカード/NICOS/VISA");
insert into credit_code_list values("453865", "NICOS");
insert into credit_code_list values("453865", "Nicos-DoCoMo-VISA");
insert into credit_code_list values("453865", "ebank-NICOS-VISA");
insert into credit_code_list values("453865", "synergy NICOS-VISA");
insert into credit_code_list values("453865", "イーバンクニコス");
insert into credit_code_list values("453865", "シナジーカード/NICOS/VISA");
insert into credit_code_list values("453868", "NICOS KETAI VISA");
insert into credit_code_list values("453868", "NICOS VISA Soo");
insert into credit_code_list values("453868", "NICOS VISA オードリー");
insert into credit_code_list values("453868", "WOWOW ぴあ NICOS VISA");
insert into credit_code_list values("453869", "ＮＩＣＯＳロードネット／ETCカード");
insert into credit_code_list values("453887", "Yahoo! JAPAN VISA");
insert into credit_code_list values("453892", "you me-VISA");
insert into credit_code_list values("453892", "you me-VISA");
insert into credit_code_list values("453892", "you me-VISA");
select sleep(1) from dual;
insert into credit_code_list values("453892", "youme-VISA");
insert into credit_code_list values("453892", "ゆめカードVISA");
insert into credit_code_list values("453892", "ゆめカードVISA");
insert into credit_code_list values("453893", "GE-VISA(旧ジーシー発行)");
insert into credit_code_list values("453897", "髙島屋VISA");
insert into credit_code_list values("453898", "TSUTAYA Wカ－ド VISA");
insert into credit_code_list values("453898", "アプラススマイルパーソナルVISA");
insert into credit_code_list values("454111", "LaOXメンバーズカード/SAISON/VISA");
insert into credit_code_list values("454114", "SAISON-VISA　（池袋西武）");
insert into credit_code_list values("454115", "CLUB ONカード《セゾン》");
insert into credit_code_list values("454115", "CLUB ONカード《セゾン》 VISA");
insert into credit_code_list values("454115", "MONEX SAISON VISA");
insert into credit_code_list values("454115", "SAISON株主優待VISA");
insert into credit_code_list values("454117", "LOWSON PASS VISA");
insert into credit_code_list values("454117", "ローソンパス(VISA)");
insert into credit_code_list values("454121", "cocoon-SAISON-VISA");
insert into credit_code_list values("454123", "MONEX-SAISON-VISA");
insert into credit_code_list values("454123", "SAISON UA-VISA");
insert into credit_code_list values("454123", "静銀セゾン");
insert into credit_code_list values("454123", "郵貯《セゾン》VISA");
select sleep(1) from dual;
insert into credit_code_list values("454124", "ＫＩＰＳパルケエスパーニャカード（UC）");
insert into credit_code_list values("454125", "セゾンゆうちょVISA");
insert into credit_code_list values("454130", "そゴーミレニアム");
insert into credit_code_list values("454130", "クラブオンカード　セゾン");
insert into credit_code_list values("454130", "セゾン-フォービート");
insert into credit_code_list values("454131", "SAISONカードVISA・五番館（北海道西武）");
insert into credit_code_list values("454131", "VISA-SAISON-UA Airlines Mileage Plus");
insert into credit_code_list values("454132", "SAISONパルコカードクラスS");
insert into credit_code_list values("454133", "SAISON UA");
insert into credit_code_list values("454133", "SEIBU PRINCE-SAISON VISA");
insert into credit_code_list values("454133", "郵貯チェックSAISON");
insert into credit_code_list values("454133", "郵貯チェックカード《セゾン》");
insert into credit_code_list values("454140", "JAF《セゾン》VISA");
insert into credit_code_list values("454140", "SAISON- @nifty");
insert into credit_code_list values("454141", "SAISON-郵貯VISA");
insert into credit_code_list values("454141", "UC");
insert into credit_code_list values("454142", "SAISON @nifty VISA");
insert into credit_code_list values("454142", "SAISON-MONEX-VISA");
insert into credit_code_list values("454142", "マイクロソフト《セゾン》カード");
insert into credit_code_list values("454143", "SAISON-VISA");
select sleep(1) from dual;
insert into credit_code_list values("454143", "郵貯《セゾン》VISA");
insert into credit_code_list values("454150", "MONEX《セゾン》カード");
insert into credit_code_list values("454151", "SAISONカードVISA・北海道西友");
insert into credit_code_list values("454152", "セゾン　KDDI");
insert into credit_code_list values("454152", "郵貯《セゾン》VISA");
insert into credit_code_list values("454156", "ビザ セゾン");
insert into credit_code_list values("454158", "りそなカード　セゾン");
insert into credit_code_list values("454158", "りそなカード　セゾンVISA");
insert into credit_code_list values("454159", "出光カードまいどプラス VISA");
insert into credit_code_list values("454161", "SAISON-VISA");
insert into credit_code_list values("454165", "@nifty SAISON VISA");
insert into credit_code_list values("454166", "@nifty SAISON-VISA");
insert into credit_code_list values("454166", "SAISON Microsoft VISA");
insert into credit_code_list values("454166", "セゾン VISA L.L.Bean Club");
insert into credit_code_list values("454167", "WOWOW-SAISON-VISA");
insert into credit_code_list values("454171", "SAISON郵貯VISA");
insert into credit_code_list values("454171", "SoftBank Card");
insert into credit_code_list values("454173", "みずほマイレージクラブセゾン");
insert into credit_code_list values("454196", "りそなカード　セゾンGOLD(VISA)");
insert into credit_code_list values("454202", "イーバンクマネーカード・クラシック");
select sleep(1) from dual;
insert into credit_code_list values("454202", "イーバンク銀行　イーバンクマネーカード・クラシック");
insert into credit_code_list values("454203", "イーバンクマネーカード");
insert into credit_code_list values("454203", "イーバンクマネーカード・ゴールド");
insert into credit_code_list values("454214", "UC-VISA Gold");
insert into credit_code_list values("454214", "jal");
insert into credit_code_list values("454214", "みずほUC-G VISA");
insert into credit_code_list values("454220", "WWF UC VISA");
insert into credit_code_list values("454220", "みずほUC-VISA一般");
insert into credit_code_list values("454224", "ＫＩＰＳパルケエスパーニャカード（UC）");
insert into credit_code_list values("454246", "jal");
insert into credit_code_list values("454248", "日産カード/UC/VISA");
insert into credit_code_list values("454252", "To Me UC-VISA一般");
insert into credit_code_list values("454271", "りそなUC-VISA");
insert into credit_code_list values("454272", "uc");
insert into credit_code_list values("454272", "uc");
insert into credit_code_list values("454273", "Honda C-card/UC/VISA");
insert into credit_code_list values("454273", "みずほUCカードセレクト");
insert into credit_code_list values("454274", "Honda C-card/UC/VISA （りそなカード）");
insert into credit_code_list values("454275", "DoCoMo UC Card VISA");
insert into credit_code_list values("454275", "UC VISA 証個");
select sleep(1) from dual;
insert into credit_code_list values("454275", "WWFカード 一般 (UC)");
insert into credit_code_list values("454275", "みずほUCVISA");
insert into credit_code_list values("454275", "みずほ銀行UC");
insert into credit_code_list values("454275", "ビックカードインターナショナル");
insert into credit_code_list values("454275", "ユーシー　セレクトビザ　セゾン発行");
insert into credit_code_list values("454285", "JR東日本");
insert into credit_code_list values("454285", "VIEW-VISA");
insert into credit_code_list values("454286", "VIEW-VISA");
insert into credit_code_list values("454286", "VIEW-VISA マイシティ新宿カード");
insert into credit_code_list values("454287", "LUMINE VIEW-Suica-VISA");
insert into credit_code_list values("454287", "Mizuho Suica");
insert into credit_code_list values("454287", "VIEW Suica");
insert into credit_code_list values("454287", "VIEW-Suica-VISA");
insert into credit_code_list values("454287", "view suica visa");
insert into credit_code_list values("454294", "ＵＣ ＶＩＳＡ（ゴールド）");
insert into credit_code_list values("454381", "top");
insert into credit_code_list values("454381", "top");
insert into credit_code_list values("454383", "top");
insert into credit_code_list values("456605", "MUFGゴールドプレステージ");
insert into credit_code_list values("456605", "UFJCard プレミオVISA");
select sleep(1) from dual;
insert into credit_code_list values("456605", "UFJワンパスVISA");
insert into credit_code_list values("456633", "MUFG ゴールド（鹿金）");
insert into credit_code_list values("456685", "名古屋カード　金ビザ");
insert into credit_code_list values("457556", "able");
insert into credit_code_list values("468512", "レクサスカード VISA Platinum - TS CUBIC");
insert into credit_code_list values("468517", "teamTOYOTA TS3-VISA");
insert into credit_code_list values("468517", "ＪＯＭＯ");
insert into credit_code_list values("468517", "トヨタ　ティーエスキュービック　ビザ　レギュラー");
insert into credit_code_list values("470086", "大丸お得意様ゴールドカード（ハウス・11桁）");
insert into credit_code_list values("470801", "中国銀行DREAMe W VISA");
insert into credit_code_list values("473063", "CALIFORNIA BANK & TRUST (キャッシュカード・VISAデビット)");
insert into credit_code_list values("479884", "E*trade VISA Debit");
insert into credit_code_list values("489784", "エポスカードVISA");
insert into credit_code_list values("490115", "NW-CITI-VISA-Gold");
insert into credit_code_list values("490120", "OMC VISA");
insert into credit_code_list values("490120", "OMC-VISA");
insert into credit_code_list values("490120", "omc");
insert into credit_code_list values("490121", "OMC VISA （リボも同じ）");
insert into credit_code_list values("490121", "OMC 郵貯VISA");
insert into credit_code_list values("490121", "OMC-VISA");
select sleep(1) from dual;
insert into credit_code_list values("490121", "イーバンクオーエムシービザ");
insert into credit_code_list values("490129", "OMC GOLD VISA");
insert into credit_code_list values("490129", "OMC-VISA");
insert into credit_code_list values("490643", "東京三菱-VISA GOLD PREMIUM");
insert into credit_code_list values("490644", "三菱東京UFJ-VISA（コンビタイプ）");
insert into credit_code_list values("490646", "三菱東京UFJ-VISA（ICクレジットカード）");
insert into credit_code_list values("490647", "UFJ");
insert into credit_code_list values("490647", "三菱東京UFJ-VISA　(ICクレジットカード)");
insert into credit_code_list values("490647", "三菱東京UFJ銀行");
insert into credit_code_list values("490648", "三菱東京UFJ-VISA （スーパーICカードSuica）");
insert into credit_code_list values("490714", "Amazon-VISA");
insert into credit_code_list values("490714", "Citi-Clear-VISA");
insert into credit_code_list values("490714", "NW-citi-VISA");
insert into credit_code_list values("490714", "WQ");
insert into credit_code_list values("490714", "citi-VISA student");
insert into credit_code_list values("490715", "CITI ELITE VISA");
insert into credit_code_list values("490715", "CITI VISA Gold");
insert into credit_code_list values("490715", "NWA-Citi-WorldPerks-VISA-Gold");
insert into credit_code_list values("490715", "citi elite");
insert into credit_code_list values("490715", "citi-VISA");
select sleep(1) from dual;
insert into credit_code_list values("492214", "東邦カードVISA");
insert into credit_code_list values("492215", "東邦カードVISAゴールド");
insert into credit_code_list values("492218", "紀陽カードVISA");
insert into credit_code_list values("492220", "ブイアイ 池田VISA");
insert into credit_code_list values("492230", "Citi VISA PLATINUM");
insert into credit_code_list values("492230", "NW-CITI-VISA-Plt");
insert into credit_code_list values("492231", "NTTグループカード-VISA");
insert into credit_code_list values("492232", "七十七カードVISA");
insert into credit_code_list values("492233", "七十七カードVISAゴールド");
insert into credit_code_list values("492242", "さぎんモテカカードVISA");
insert into credit_code_list values("492253", "北国VISAカード");
insert into credit_code_list values("492254", "東京VISA");
insert into credit_code_list values("492255", "東京VISA GOLD");
insert into credit_code_list values("492256", "北国VISAゴールド");
insert into credit_code_list values("492257", "群銀カードVISA");
insert into credit_code_list values("492258", "群銀カードVISAゴールド");
insert into credit_code_list values("492259", "三重銀カードVISA");
insert into credit_code_list values("492260", "三重銀カードVISAゴールド");
insert into credit_code_list values("492263", "四国しんきんVISAカード");
insert into credit_code_list values("492267", "住信VISA");
select sleep(1) from dual;
insert into credit_code_list values("492268", "住信VISAゴールドカード");
insert into credit_code_list values("492268", "住信ロードサービスVISA-G");
insert into credit_code_list values("492269", "あさひVISA");
insert into credit_code_list values("492269", "あさひデルタVISA");
insert into credit_code_list values("492269", "とらのあな-りそな-VISA");
insert into credit_code_list values("492269", "りそな");
insert into credit_code_list values("492269", "りそな　東横イン４＆５");
insert into credit_code_list values("492271", "りそなカード");
insert into credit_code_list values("492271", "早稲田ＧＯＬＤカード");
insert into credit_code_list values("492273", "やまぎんクレジットVISAゴールド");
insert into credit_code_list values("492274", "ごうぎんクレジット（ＶＪＡ）　ＶＩＳＡ");
insert into credit_code_list values("492275", "ごうぎんDuoカードVISA");
insert into credit_code_list values("492276", "九州しんきんVISA");
insert into credit_code_list values("492278", "信金VISA");
insert into credit_code_list values("492285", "道銀キャッシュ・クレジットカードVISA");
insert into credit_code_list values("492286", "道銀キャッシュ・クレジットカードVISAゴールド");
insert into credit_code_list values("492287", "福岡銀行arecore-VISA");
insert into credit_code_list values("492313", "NFS-NICOS-VISA");
insert into credit_code_list values("492313", "NICOS郵貯VISA");
insert into credit_code_list values("492313", "さくらやNICOS VISA");
select sleep(1) from dual;
insert into credit_code_list values("492313", "ニコス VISA （一般カード）");
insert into credit_code_list values("492313", "ニコス-国際ボランティア貯金カード-VISA");
insert into credit_code_list values("492314", "NICOS-VISA(ncom)");
insert into credit_code_list values("492314", "ＮＩＣＯＳ　ＶＩＳＡカード");
insert into credit_code_list values("492314", "オレンジメイツカ－ド（NICOS）");
insert into credit_code_list values("492314", "コーエーカード（NICOS）");
insert into credit_code_list values("492339", "全日鰤");
insert into credit_code_list values("492341", "NICOS VISA ぴあ");
insert into credit_code_list values("492343", "NICOS-VISA");
insert into credit_code_list values("492343", "ニコス郵貯ジョイントカード-VISA");
insert into credit_code_list values("492344", "NICOS VISA");
insert into credit_code_list values("492346", "NICOS-VISA(ぴあ)");
insert into credit_code_list values("492346", "ニコス郵貯ジョイントカード-VISA");
insert into credit_code_list values("492358", "LIFE-VISA");
insert into credit_code_list values("492358", "ライフ");
insert into credit_code_list values("492371", "KC VISA");
insert into credit_code_list values("492371", "Rakuten-VISA");
insert into credit_code_list values("492380", "It'sカード NICOS-VISA");
insert into credit_code_list values("492381", "NICOS アスキーカード");
insert into credit_code_list values("492386", "ニコス郵貯ジョイントカード-VISA");
select sleep(1) from dual;
insert into credit_code_list values("492387", "NICOS VISA ぴあ");
insert into credit_code_list values("492387", "NICOSぴあカード");
insert into credit_code_list values("492390", "[ Ena NICOS VISA");
insert into credit_code_list values("492391", "NICOS VISA ぴあ");
insert into credit_code_list values("492391", "昭和シェル X-CARD NICOS VISA");
insert into credit_code_list values("492397", "郵貯NICOS VISA");
insert into credit_code_list values("493795", "@niftyパワーオリコ VISA");
insert into credit_code_list values("493795", "Orico VISA");
insert into credit_code_list values("493795", "オリコ　ユーシー　ビザ");
insert into credit_code_list values("493795", "オリコカード");
insert into credit_code_list values("493795", "オリコカード");
insert into credit_code_list values("493795", "コジマ・オリコ・ＶＩＳＡ");
insert into credit_code_list values("494928", "PNC Bank VISA");
insert into credit_code_list values("498000", "ANA SMC VISA G");
insert into credit_code_list values("498000", "ANA-SFC-SMC-VISA-G");
insert into credit_code_list values("498000", "DCMX");
insert into credit_code_list values("498000", "Hilton三井住友VISA Gold");
insert into credit_code_list values("498000", "Panasonic-VISA");
insert into credit_code_list values("498000", "SMC-VISA-GOLD");
insert into credit_code_list values("498000", "smc");
select sleep(1) from dual;
insert into credit_code_list values("498000", "visa");
insert into credit_code_list values("498000", "ＶＩＳＡ");
insert into credit_code_list values("498000", "キャリストカード（GOLD)");
insert into credit_code_list values("498000", "ソニーカードゴールド");
insert into credit_code_list values("498000", "三井住友");
insert into credit_code_list values("498000", "三井住友");
insert into credit_code_list values("498000", "三井住友");
insert into credit_code_list values("498000", "三井住友One'sCard（YG)");
insert into credit_code_list values("498000", "三井住友VISA");
insert into credit_code_list values("498000", "三井住友YG");
insert into credit_code_list values("498000", "三井住友ＶＩＳＡゴールド（ヤング）★");
insert into credit_code_list values("498000", "三井住友金");
insert into credit_code_list values("498001", "SMC-VISA-Tuo");
insert into credit_code_list values("498001", "ANA elio-VISA");
insert into credit_code_list values("498001", "ANA elio-VISA");
insert into credit_code_list values("498001", "AOYAMA-SMC-VISA");
insert into credit_code_list values("498001", "JC(日本青年会議所）三井住友VISA　Classic");
insert into credit_code_list values("498001", "JNB SMC-VISA");
insert into credit_code_list values("498001", "LAOX eLIO VISA");
insert into credit_code_list values("498001", "My Sony Card");
select sleep(1) from dual;
insert into credit_code_list values("498001", "My Sony Card(eLIOカード）");
insert into credit_code_list values("498001", "SFC-ANA-VISA");
insert into credit_code_list values("498001", "SFC-VISA(plalaカード)");
insert into credit_code_list values("498001", "SMBC ANA-VISA");
insert into credit_code_list values("498001", "SMC unicef VISA");
insert into credit_code_list values("498001", "SMC-ANA-VISA-St");
insert into credit_code_list values("498001", "SMC-VISA");
insert into credit_code_list values("498001", "SMC-VISA クラシックA");
insert into credit_code_list values("498001", "ソニーファイナンス BeneficioCard (elio 企業提携)");
insert into credit_code_list values("498001", "ソニーファイナンス　ヨドバシ");
insert into credit_code_list values("498001", "ソニーファイナンス丸の内VISA");
insert into credit_code_list values("498001", "慶應カード -st");
insert into credit_code_list values("498001", "三井住友ＶＩＳＡ");
insert into credit_code_list values("498003", "123");
insert into credit_code_list values("498003", "SMC-VISA");
insert into credit_code_list values("498003", "SMCクラシックA（学生）-VISA");
insert into credit_code_list values("498003", "三井住友 バーチャル VISA");
insert into credit_code_list values("498003", "三井住友VISA miniクラシックカード");
insert into credit_code_list values("498003", "三井住友VISAクラシック");
insert into credit_code_list values("498003", "三井住友VISA舗袷・彊爪");
select sleep(1) from dual;
insert into credit_code_list values("498003", "三井住友ＶＩＳＡカード");
insert into credit_code_list values("498003", "三井住友カード");
insert into credit_code_list values("498003", "蜜墨visa");
insert into credit_code_list values("498005", "DoCoMo三井住友VISAカード");
insert into credit_code_list values("498005", "MJC-VISA");
insert into credit_code_list values("498005", "NKLDSAJK");
insert into credit_code_list values("498005", "SMBC CARD VISA (iD一体)");
insert into credit_code_list values("498005", "楽天カードーVISA");
insert into credit_code_list values("498005", "三井");
insert into credit_code_list values("498005", "三井住友");
insert into credit_code_list values("498005", "三井住友One's Card　VISA");
insert into credit_code_list values("498005", "三井住友VISAカード U-Zu");
insert into credit_code_list values("498005", "三井住友VISAッピ");
insert into credit_code_list values("498005", "三井住友VISAワンダー");
insert into credit_code_list values("498005", "三井住友カード/MJC");
insert into credit_code_list values("498005", "三越VISA");
insert into credit_code_list values("498006", "HANA PLUS VISA");
insert into credit_code_list values("498007", "NTTドコモ - DCMX - VISA");
insert into credit_code_list values("498009", "三井住友-京王パスポート-VISA");
insert into credit_code_list values("498011", "SMC VISA Platinum");
select sleep(1) from dual;
insert into credit_code_list values("498020", "三井住友VISAビジネスカードGOLD");
insert into credit_code_list values("498021", "三井住友VISAビジネスカードclasic");
insert into credit_code_list values("498022", "SMC-VISA CORPORATE");
insert into credit_code_list values("498036", "九州VISA");
insert into credit_code_list values("498037", "九州VISAカード");
insert into credit_code_list values("498040", "京葉銀VISAカード");
insert into credit_code_list values("498041", "京葉銀VISAゴールドカード");
insert into credit_code_list values("498042", "北陸カードVISA(一般)");
insert into credit_code_list values("498043", "北陸カードVISA(ゴールド)");
insert into credit_code_list values("498052", "いわぎんVISAクラシックカード");
insert into credit_code_list values("498053", "いわぎんＶＩＳＡゴールドカード");
insert into credit_code_list values("498060", "NC北海専門店会　VISA");
insert into credit_code_list values("498061", "GE DELL餅斟英餅彌彊爪VISA");
insert into credit_code_list values("498061", "GE-VISA");
insert into credit_code_list values("498061", "GECF-VISA JARL CARD/SMBC発行");
insert into credit_code_list values("498061", "NCおびひろ VISA");
insert into credit_code_list values("498061", "第一信販NC VISA");
insert into credit_code_list values("498062", "NCとまこまい");
insert into credit_code_list values("498062", "札幌信用販売　ＶＩＳＡ");
insert into credit_code_list values("498066", "イズミヤVISAカード");
select sleep(1) from dual;
insert into credit_code_list values("498066", "ポケット");
insert into credit_code_list values("498066", "マイカルVISA");
insert into credit_code_list values("498066", "住商カード");
insert into credit_code_list values("498070", "みなとVISAカード");
insert into credit_code_list values("498071", "みなとカードVISAゴールド");
insert into credit_code_list values("498073", "九州VISA　クラシック");
insert into credit_code_list values("498075", "visacard");
insert into credit_code_list values("498075", "しんきんクレジットサービス　ロードサービスビザ");
insert into credit_code_list values("498605", "UFJ-VISA K-power");
insert into credit_code_list values("498611", "イトー");
insert into credit_code_list values("498611", "ｲﾄｰﾖｰｶﾄﾞｰＶＩＳＡ");
insert into credit_code_list values("498611", "ｲﾄｰﾖｰｶﾄﾞｰＶＩＳＡ");
insert into credit_code_list values("498631", "DoCoMo UFJ-VISA");
insert into credit_code_list values("498631", "Honda C-card/UFJ/VISA");
insert into credit_code_list values("498632", "APA-JR-UFJ-VISA(アパガード)");
insert into credit_code_list values("498632", "UFJ SNOOPY Edy（黒犬）");
insert into credit_code_list values("498632", "UFJ-VISA");
insert into credit_code_list values("498632", "UFJ-VISA K-power");
insert into credit_code_list values("498632", "UFJ-VISA VIASO");
insert into credit_code_list values("498632", "UFJオールワン一体型");
select sleep(1) from dual;
insert into credit_code_list values("498632", "UFJｶｰﾄﾞ VISA （一般ｶｰﾄﾞ）");
insert into credit_code_list values("498632", "スカイマーク　UFJ　VISA");
insert into credit_code_list values("498636", "Smartplus (UFJカード)");
insert into credit_code_list values("498638", "UFJ VISA");
insert into credit_code_list values("498647", "パスタウンカード（UFJ）");
insert into credit_code_list values("498651", "UFJ-FinancialOne-VISA");
insert into credit_code_list values("498651", "visa");
insert into credit_code_list values("498658", "J-WEST(UFJ VISA)");
insert into credit_code_list values("498660", "UFJ,");
insert into credit_code_list values("498681", "UFJ中京カード");
insert into credit_code_list values("498681", "UFJ中京カード");
insert into credit_code_list values("498681", "ｊｃｂ");
insert into credit_code_list values("498695", "CF-コスモカードVISA");
insert into credit_code_list values("498695", "EXPRESS CARD (CF)");
insert into credit_code_list values("498695", "aaa");
insert into credit_code_list values("498695", "セントラルファイナンス");
insert into credit_code_list values("501090", "TOPホワイト");
insert into credit_code_list values("501091", "東急TOP（ハウス）");
insert into credit_code_list values("501098", "QPoint-TOP");
insert into credit_code_list values("504572", "みずほ銀行（旧）エムタウン支店・インターナショナルキャッシュカード（Cirrus提携）");
select sleep(1) from dual;
insert into credit_code_list values("512780", "SBIレギュラー");
insert into credit_code_list values("512780", "STAR FLYER (SBIカード)");
insert into credit_code_list values("517895", "City National Bank of West Virginia - Gold Debit Matercard");
insert into credit_code_list values("518691", "アイフル e-まちタウンPPC MasterCard");
insert into credit_code_list values("520175", "東☆マスター");
insert into credit_code_list values("520809", "UFJ-Financial One-MasterCard");
insert into credit_code_list values("520809", "UFJ一般マスター");
insert into credit_code_list values("520809", "UFJﾏｽﾀｰ（一般ｶｰﾄﾞ）");
insert into credit_code_list values("520809", "スカイマーク　UFJ　Master");
insert into credit_code_list values("520831", "DoCoMo UFJ Card Master");
insert into credit_code_list values("520836", "Smartplus (UFJ-Master)");
insert into credit_code_list values("520840", "UCS-MasterCard(一般)");
insert into credit_code_list values("520847", "UFJ Pastown Card MasterCard");
insert into credit_code_list values("520848", "UFJ 京成カード Master");
insert into credit_code_list values("520848", "UFJマスター");
insert into credit_code_list values("520849", "UFJ vodafone card 東海");
insert into credit_code_list values("520858", "J-WESTエクスプレスMaster");
insert into credit_code_list values("520858", "J-WESTベーシックMaster");
insert into credit_code_list values("520882", "UCS enta");
insert into credit_code_list values("520882", "UCS-MasterCard");
select sleep(1) from dual;
insert into credit_code_list values("520882", "UCS-MasterCard(ゴールド)");
insert into credit_code_list values("520882", "UCS　KARUWAZAカード");
insert into credit_code_list values("521010", "BEST_Denki-KC-MASTER");
insert into credit_code_list values("521010", "KC-Master");
insert into credit_code_list values("521010", "KC-千葉ロッテマリーンズ-Master");
insert into credit_code_list values("521010", "TI・Mobile-KC-Master");
insert into credit_code_list values("521010", "楽天KC JAF ﾏｽﾀｰ");
insert into credit_code_list values("521102", "ニッセンＧＥ　マジカルクラブカード");
insert into credit_code_list values("521210", "百十四 DC");
insert into credit_code_list values("521465", "E-NEXCO pass NICOS Master");
insert into credit_code_list values("521465", "ENEOS-NICOS-MASTER");
insert into credit_code_list values("521487", "Yahoo! JAPAN Master");
insert into credit_code_list values("521488", "youme-Master");
insert into credit_code_list values("521913", "CF ブリジストン　マスター");
insert into credit_code_list values("521915", "CF-Naster(JR東海EXPRESS CARD)");
insert into credit_code_list values("524340", "SBI Platinum");
insert into credit_code_list values("524805", "28-ORICO-HUKU2PLUSカード(紳士服のはるやま)");
insert into credit_code_list values("524805", "@NIFTY Orico-Master");
insert into credit_code_list values("524805", "FORCEA Orico-Master");
insert into credit_code_list values("524805", "ORICO-HUKU2PLUSカード");
select sleep(1) from dual;
insert into credit_code_list values("524805", "Orico Gold Master Card iGold");
insert into credit_code_list values("524805", "Orico Gold MasterCard iGold");
insert into credit_code_list values("524805", "Orico(ナジャヴ倶楽部)-MASTER");
insert into credit_code_list values("524805", "Orico");
insert into credit_code_list values("524805", "Orico-@nifty-Master");
insert into credit_code_list values("524805", "Orico-Animate-Master");
insert into credit_code_list values("524805", "Orico-M Card-Master");
insert into credit_code_list values("524805", "Orico-Master @nifty常時安全カード");
insert into credit_code_list values("524805", "TIPNESS Orico鱒");
insert into credit_code_list values("524805", "Yahoo!Japan-Master(Orico)");
insert into credit_code_list values("524805", "オリコ");
insert into credit_code_list values("524805", "オリコiGold Master");
insert into credit_code_list values("524805", "オリコ　イクスピアリカード　マスター");
insert into credit_code_list values("524805", "オリコ・アパマンショップカード");
insert into credit_code_list values("524805", "オリコークラブアライアンス");
insert into credit_code_list values("524805", "サンカード・オリコＭ");
insert into credit_code_list values("524805", "フタバファーストOrico-Master");
insert into credit_code_list values("524806", "Orico Gold Master Card UPty");
insert into credit_code_list values("524806", "Orico MasterCard UPty");
insert into credit_code_list values("524806", "Orico らき☆すたカードUpty");
select sleep(1) from dual;
insert into credit_code_list values("524806", "Orico-Rider's Assist UPty-Master");
insert into credit_code_list values("525003", "MIZUHO UC GOLD");
insert into credit_code_list values("525006", "YamahaFeelingClub-UC-Master");
insert into credit_code_list values("525014", "UC Master Gold");
insert into credit_code_list values("525022", "mizuho uc master");
insert into credit_code_list values("525035", "UC-Master Gold(みずほマイレージ)");
insert into credit_code_list values("525036", "Mizuho Mileage Club (SELECT)");
insert into credit_code_list values("525036", "UC-Master(みずほマイレージ)");
insert into credit_code_list values("525048", "NISSAN CARD　MASTER");
insert into credit_code_list values("525048", "UCマスター");
insert into credit_code_list values("525052", "To Me UC-Master一般");
insert into credit_code_list values("525069", "JTB UC-Master");
insert into credit_code_list values("525071", "@nifty UC Master");
insert into credit_code_list values("525072", "BIC UC Master");
insert into credit_code_list values("525072", "DoCoMo UC Card MASTER");
insert into credit_code_list values("525072", "MIZUHO UC select Master");
insert into credit_code_list values("525072", "UC");
insert into credit_code_list values("525072", "UC WWFセレクト MASTER");
insert into credit_code_list values("525072", "UC-Master　トランスルーセント");
insert into credit_code_list values("525072", "UC-Master、みずほUC-Master");
select sleep(1) from dual;
insert into credit_code_list values("525072", "VISA");
insert into credit_code_list values("525072", "三越 UC Master");
insert into credit_code_list values("525073", "UC・マイレージプラスセレクト・マスター");
insert into credit_code_list values("525073", "UCトランスルーセントMaster(イルカ)");
insert into credit_code_list values("525073", "UNITED Mileage Plus UC Card（マスター）");
insert into credit_code_list values("525073", "りそなUC Master一般");
insert into credit_code_list values("525087", "LUMINE-View-Master");
insert into credit_code_list values("525087", "VIEW Suica MASTER");
insert into credit_code_list values("525087", "VIEW Suica MasterCard");
insert into credit_code_list values("525087", "View-Suica-Master");
insert into credit_code_list values("525113", "NICOS MASTER ぴあ");
insert into credit_code_list values("525113", "NICOS-MASTER-CAMPUS");
insert into credit_code_list values("525210", "SAISON Master");
insert into credit_code_list values("525210", "セゾンUAカレッジ");
insert into credit_code_list values("525212", "SAISON Master");
insert into credit_code_list values("525214", "セゾン　UA　Master");
insert into credit_code_list values("525215", "SAISON");
insert into credit_code_list values("525215", "SAIS◎N-MASTER");
insert into credit_code_list values("525215", "クラブオン・セゾンMaster");
insert into credit_code_list values("525224", "SAISON-master");
select sleep(1) from dual;
insert into credit_code_list values("525231", "SAISON Master");
insert into credit_code_list values("525233", "SEIBU PRINCE-SAISON-Master");
insert into credit_code_list values("525236", "saison");
insert into credit_code_list values("525240", "Mitsui Outlet Park SAISON Master");
insert into credit_code_list values("525240", "SAISON UA-Master");
insert into credit_code_list values("525243", "SAISON西友株主ご優待");
insert into credit_code_list values("525252", "SAISON UA Master");
insert into credit_code_list values("525258", "りそなカード セゾン Master");
insert into credit_code_list values("525259", "SAISON 出光 mydo plus Master");
insert into credit_code_list values("525265", "Ｖｏｄａｆｏｎｅ　ＳＡＩＳＯＮ （Ｍ）");
insert into credit_code_list values("525265", "セゾンUA 一般");
insert into credit_code_list values("525267", "WOWOW《セゾン》カード");
insert into credit_code_list values("525290", "セゾン Master UA カード(ゴールド)");
insert into credit_code_list values("525291", "SOGO-Millennium-SAISON-MASTER-GOLD");
insert into credit_code_list values("525701", "OMC-Master");
insert into credit_code_list values("525701", "OMC-Master");
insert into credit_code_list values("525701", "OMC-Mastercard");
insert into credit_code_list values("525701", "ゆうちょ OMC Master");
insert into credit_code_list values("527916", "TOP GOLD");
insert into credit_code_list values("527916", "top");
select sleep(1) from dual;
insert into credit_code_list values("527918", "GRANDBERRY TOP Master");
insert into credit_code_list values("527918", "TOKYU PLAZA CARD プラザプラス(TOP)");
insert into credit_code_list values("527930", "DCカードJizileマスター");
insert into credit_code_list values("527930", "DC上野商店街連合Master（UENOカード）");
insert into credit_code_list values("527934", "DC-JALMaster-CLUB-A");
insert into credit_code_list values("527934", "DC-JALMaster-普通");
insert into credit_code_list values("527935", "DC-Master-G");
insert into credit_code_list values("527935", "東京三菱DC-Master-G");
insert into credit_code_list values("527939", "クラブドンペンカード DC-Master");
insert into credit_code_list values("527942", "東京海上DCマスターカード");
insert into credit_code_list values("527951", "DC GONZO Master GOLD");
insert into credit_code_list values("527951", "JAL CLUB-A DC/MasterCard Gold");
insert into credit_code_list values("527951", "JGC CLUB-A DC/MasterCard Gold");
insert into credit_code_list values("527951", "日本盲導犬協会カード DC/MasterCard Gold");
insert into credit_code_list values("527970", "ＤＣ");
insert into credit_code_list values("527970", "ＤＣ");
insert into credit_code_list values("527978", "あしぎんDC Master Gold");
insert into credit_code_list values("528371", "DoCoMo NTT-L Master");
insert into credit_code_list values("528371", "SCENE UC Master (NTT-L)");
insert into credit_code_list values("528371", "ちば興銀UC");
select sleep(1) from dual;
insert into credit_code_list values("528371", "りそなカード UC Master");
insert into credit_code_list values("528388", "旧山一證券一般(廃業によりUC直轄に移管)");
insert into credit_code_list values("528577", "ふくぎん BANK CARD Master");
insert into credit_code_list values("529605", "UFJ スヌーピープレミオ Master");
insert into credit_code_list values("529605", "UFJ スヌーピー金");
insert into credit_code_list values("529605", "UFJ プレミオカード");
insert into credit_code_list values("529605", "UFJ-KKR Master");
insert into credit_code_list values("529681", "ＵＦＪ");
insert into credit_code_list values("529685", "名古屋カード　金マスター");
insert into credit_code_list values("530189", "九州カードMasterCardゴールド");
insert into credit_code_list values("530230", "MITSUI SUMITOMO MasterCard GOLD");
insert into credit_code_list values("530231", "SMC MasterGold Pt");
insert into credit_code_list values("530231", "三井住友　ヤングゴールドマスター");
insert into credit_code_list values("530232", "SMC ANA Master Gold");
insert into credit_code_list values("530248", "さぎんモテカカードゴールドマスター");
insert into credit_code_list values("530258", "さぎんモテカカードMasterゴールド");
insert into credit_code_list values("530440", "スルガマスターゴールドカード");
insert into credit_code_list values("530660", "りそな　OMNI-master");
insert into credit_code_list values("531280", "イオンクレジットサービス・イオンカード(Master)");
insert into credit_code_list values("531284", "AEON Master 郵貯共用");
select sleep(1) from dual;
insert into credit_code_list values("531284", "イオンMaster");
insert into credit_code_list values("531289", "MJC-AEON-Master");
insert into credit_code_list values("531289", "イオン 日本テレコム Master");
insert into credit_code_list values("531289", "イオン・I love 代官山");
insert into credit_code_list values("531291", "JACCS北海道日本ハムファイターズＦＣカード-Master");
insert into credit_code_list values("531291", "KMA-JACCS-Master");
insert into credit_code_list values("531291", "Sofmap-JACCS");
insert into credit_code_list values("531293", "JACCS-コジマカード");
insert into credit_code_list values("532171", "jtb-master");
insert into credit_code_list values("533489", "九州カードMasterCardスタンダード");
insert into credit_code_list values("533490", "SMC-Master クラシックA");
insert into credit_code_list values("533491", "SMC-ANA-Master-St");
insert into credit_code_list values("533491", "SMC-ANA-Master一般");
insert into credit_code_list values("533491", "三井住友");
insert into credit_code_list values("533494", "SMBC ANA-MASTER");
insert into credit_code_list values("533508", "さぎんモテカカードマスター(女性向)");
insert into credit_code_list values("533550", "スルガマスターカード");
insert into credit_code_list values("535491", "SMC-ANA-Master-学生");
insert into credit_code_list values("535701", "OMC ローソンカード");
insert into credit_code_list values("540601", "CITI-G/Master");
select sleep(1) from dual;
insert into credit_code_list values("540601", "CITIBANK(GOLD)");
insert into credit_code_list values("540997", "UBOC Master デビット");
insert into credit_code_list values("540997", "UNION BANK OF CALIFORNIA （Masterデビット)");
insert into credit_code_list values("543472", "りゅうぎんDCパートナーVISA");
insert into credit_code_list values("543616", "アコム-Master");
insert into credit_code_list values("543616", "アコム-Master");
insert into credit_code_list values("543616", "アコムmaster");
insert into credit_code_list values("543816", "武富士　マスター");
insert into credit_code_list values("543817", "citi クリア-Master");
insert into credit_code_list values("543817", "シティカードジャパン クリアカードMaster");
insert into credit_code_list values("544251", "くらしらくカード Master (ポケットカード)");
insert into credit_code_list values("544253", "P-one master");
insert into credit_code_list values("544254", "P-one card Master");
insert into credit_code_list values("544254", "ポケットカード Master");
insert into credit_code_list values("544254", "マイカルブルー MasterCard");
insert into credit_code_list values("545285", "AOYAMA CARD（発行元ライフ）");
insert into credit_code_list values("545285", "LIFE　踊る大走査線　マスターカード");
insert into credit_code_list values("545285", "Life-Master");
insert into credit_code_list values("545285", "コメリ　ＡＱＵＡカード　ライフマスター");
insert into credit_code_list values("545285", "ライフカード F.S.Ca");
select sleep(1) from dual;
insert into credit_code_list values("546001", "CITI-G/Master");
insert into credit_code_list values("557851", "TS3-M-G");
insert into credit_code_list values("557852", "ＴＳ３カード［ビジネス］MASTER　一般");
insert into credit_code_list values("561018", "Sonybank Moneykitグローバル (JPモルガンチェース提携)");
insert into credit_code_list values("571100", "P-ONE");
insert into credit_code_list values("588902", "citi Bank cash card");
insert into credit_code_list values("588902", "質キャッシュカード");
insert into credit_code_list values("600053", "えらべる倶楽部 クレ無 （JTBベネフィット福利厚生）");
insert into credit_code_list values("610190", "JTB TRAVEL POINT CARD");
insert into credit_code_list values("622920", "三井住友銀聯カード");
insert into credit_code_list values("650230", "東急TOP (現金専用)");
insert into credit_code_list values("690005", "TS3 TRBM (国際ブランド無しハウスカード)");
insert into credit_code_list values("690007", "PiTaPa ベーシック");
insert into credit_code_list values("690009", "エポスカード 仮カード");
insert into credit_code_list values("690011", "DCMXmini");
insert into credit_code_list values("690011", "三井住友カードiD");
insert into credit_code_list values("690101", "丸井の赤いカード");
insert into credit_code_list values("691100", "伊勢丹 アイカード");
insert into credit_code_list values("691131", "高島屋友の会（ローズサークル）");
insert into credit_code_list values("692200", "高島屋　ゴールドカード");
select sleep(1) from dual;
insert into credit_code_list values("693050", "イオンプロパー");
insert into credit_code_list values("695001", "日経BP NICOS");
insert into credit_code_list values("695002", "NICOS プロパー国内専用");
insert into credit_code_list values("695002", "NICOS-JRA");
insert into credit_code_list values("695017", "エネオス・ニコス");
insert into credit_code_list values("695017", "ニコス");
insert into credit_code_list values("695020", "NICOS スマートプラス[カード型]");
insert into credit_code_list values("699110", "JACCS-Club Endeavor");
insert into credit_code_list values("699876", "MLカード");
insert into credit_code_list values("700000", "JCB ETC する～カード");
insert into credit_code_list values("700001", "JCB ETC する～カード");
insert into credit_code_list values("706021", "ライフ ETCカード");
insert into credit_code_list values("720011", "NICOS ETC-Plus(親カード　NICOS VISA）");
insert into credit_code_list values("725020", "楽天KC ETCカード");
insert into credit_code_list values("750000", "JCB EXXONMOBILL Corporate Plus");
insert into credit_code_list values("780001", "三井住友カード ETCカード");
insert into credit_code_list values("780016", "りそなカード　ETC");
insert into credit_code_list values("780052", "DREAMe ETC CARD");
insert into credit_code_list values("800102", "日産カード(ハウス)");
insert into credit_code_list values("800196", "日産フィナンシャルサービス・NISSAN CARD");
select sleep(1) from dual;
insert into credit_code_list values("800375", "ＵＣ　ETC");
insert into credit_code_list values("820000", "ＤＣ　ETC");
insert into credit_code_list values("830088", "EMCC");
insert into credit_code_list values("840100", "UFJ ETCカード");
insert into credit_code_list values("850030", "jcb");
insert into credit_code_list values("851223", "4545");
insert into credit_code_list values("860100", "SAISON ETCカード");
insert into credit_code_list values("861000", "IDEMITSU ETC CARD");
insert into credit_code_list values("880012", "ETC-OMC");
insert into credit_code_list values("910000", "Orico ETC CARD");
insert into credit_code_list values("920001", "トヨタファイナンス　ETC");
insert into credit_code_list values("930000", "ＣＦ　ETC");
insert into credit_code_list values("988106", "Orico Loan Card CREST");
set names sjis;

