
DROP DATABASE IF EXISTS EC_11;

CREATE DATABASE IF NOT EXISTS EC_11;
USE EC_11;

DROP TABLE IF EXISTS GOODS;
DROP TABLE IF EXISTS CUSTOMER_INFO;
DROP TABLE IF EXISTS ORDER_INFO;
DROP TABLE IF EXISTS CART;


CREATE TABLE IF NOT EXISTS GOODS(
GOODS_ID INT(100) AUTO_INCREMENT,
GOODS_NAME VARCHAR(255) NOT NULL,
STOCK INT(50),
PRICE INT,
PRIMARY KEY(GOODS_ID)
);


CREATE TABLE IF NOT EXISTS CUSTOMER_INFO(
CUSTOMER_ID INT(100)  AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(255) NOT NULL,
CUSTOMER_PASS VARCHAR(255) UNIQUE NOT NULL,
MAILAD  VARCHAR(255) NOT NULL,
POSTCODE  VARCHAR(7) NOT NULL,
ADDRESS  VARCHAR(255) NOT NULL,
TELNUMBER VARCHAR(11) NOT NULL,
REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(CUSTOMER_ID)
);


CREATE TABLE IF NOT EXISTS ORDER_INFO(
CUSTOMER_ID INT(100),
GOODS_ID INT(100),
ORDER_COUNT INT(100),
TOTAL_AMOUNT INT,
PURCHASEDAY TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_INFO(CUSTOMER_ID),
FOREIGN KEY(GOODS_ID) REFERENCES GOODS(GOODS_ID)
);

CREATE TABLE IF NOT EXISTS CART(
NAME VARCHAR(255) NOT NULL,
GOODS_NAME VARCHAR(255) NOT NULL,
SALES_NUMBER INT(100) NOT NULL,
PRICE INT NOT NULL,
TOTAL_AMOUNT INT NOT NULL
);

