
insert into site values
(  1,'BOOK MANAGER 1409','http://www.internousdev.com/bookmanager09','某大手書店向け 書籍管理サイト')
(  2,'EC 1410','http://www.internousdev.com/ec10/','日本酒・地酒販売サイト','チケット',null,null),
(  3,'ATTENDANCE','http://www.internousdev.com/attendance/','某企業向け 勤怠管理サイト',"レンタル",null,null),
(  4,'CHIKEZON','http://www.internousdev.com/chikezon/','チョコレート販売サイト',"グルメ",null,null),
(  5,'ODEN','http://www.internousdev.com/oden/',"和菓子販売サイト","グルメ",null,null),
(  6,'SAKATIKE','http://www.internousdev.com/sakatike/',"ラーメン販売サイト","グルメ",null,null);
(  7,'UESTO','http://www.inernousdev.com/uesto/'),
(  8,'TOURTIKE','http://www.internousdev.com/tourtike/'),
(  9,'SOLARE','http://www.internousdev.com/solare/'),
( 10,'WORLD TRAVEL''http://www.internousdev.com/worldtravel/'),
( 11,'YOU JUST JEWELRY','http://www.internousdev.com/youjustjewelry'),
( 12,'LA-POUPEE','http://www.internousdev.com/la-poupee/'),
( 13,'UCYCLE','http://www.internousdev.com/ucycle/'),
( 14,'BASEBALL TICKET','http://www.internousdev.com/baseballticket'),
( 15,'ICHIGO ICHIE','http://www.internousdev.com/ichigoichie/'),
( 16,'LIVE TICKETS','http://www.internousdev.com/livetickets/'),
( 17,'TBOX','http://www.internousdev.com/tbox/'),
( 18,'G-TICKETS','http://www.g'),
( 19,'MUSICAL'),
( 20,'BIG GALAXY'),
( 21,'K-HOME'),
( 22,'AQUQRIUM'),
( 23,'LEREVE'),
( 24,'SHIZUKU'),
( 25,'FOOT PRINTER'),
( 26,'UKIUKI UTOPIA'),
( 27,'PIZZA SEIJIN'),
( 28,'CHOCO TIME'),
( 29,'CINEMA JAPAN'),
( 30,'KINNOSAWA'),
( 31,'RAKURAKU'),
( 32,'KURUYAMA'),
( 33,'MACKEY PARK'),
( 34,'SAKATIKE'),
( 35,'GEKIDAN ROADSHOW'),
( 36,'GPS COFFEE'),
( 37,'MIRA-MODE'),
( 38,'REWRITE'),
( 39,'SAMURAI'),
( 40,'INTERNOUSDEV'),
( 41,'NAGOMI'),
( 41,'NOEL'),
( 42,'LUSSO'),
( 43,'DEBUT'),
( 44,'NADESHIKO'),
( 45,'SHIKI'),