use openconnect;
insert into site(site_id,site_name,site_url,picture,year)
values
(  1,'BOOK MANAGER 1409','http://www.internousdev.com/bookmanager09','yasai1.jpg',2014),
(  2,'EC 1410','http://www.internousdev.com/ec10/','yasai1.jpg',2014),
(  3,'ATTENDANCE','http://www.internousdev.com/attendance/','yasai1.jpg',2014),
(  4,'CHIKEZON','http://www.internousdev.com/chikezon/','yasai1.jpg',2014),
(  5,'ODEN','http://www.internousdev.com/oden/','yasai1.jpg',2014),
(  6,'SAKATIKE','http://www.internousdev.com/sakatike/','yasai1.jpg',2014),
(  7,'UESTO','http://www.inernousdev.com/uesto/','yasai1.jpg',2014),
(  8,'TOURTIKE','http://www.internousdev.com/tourtike/','yasai1.jpg',2014),
(  9,'SOLARE','http://www.internousdev.com/solare/','yasai1.jpg',2014),
( 10,'WORLD TRAVEL','http://www.internousdev.com/worldtravel/','yasai1.jpg',2014),
( 11,'YOU JUST JEWELRY','http://www.internousdev.com/youjustjewelry','yasai1.jpg',2014),
( 12,'LA-POUPEE','http://www.internousdev.com/la-poupee/','yasai1.jpg',2014),
( 13,'UCYCLE','http://www.internousdev.com/ucycle/','yasai1.jpg',2014),
( 14,'BASEBALL TICKET','http://www.internousdev.com/baseballticket','yasai1.jpg',2014),
( 15,'ICHIGO ICHIE','http://www.internousdev.com/ichigoichie/','yasai1.jpg',2014),
( 16,'LIVE TICKETS','http://www.internousdev.com/livetickets/','yasai1.jpg',2014),
( 17,'TBOX','http://www.internousdev.com/tbox/','yasai1.jpg',2014),
( 18,'G-TICKETS','http://www.internousdev.com/g-tickets/','yasai1.jpg',2014),
( 19,'MUSICAL','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 20,'BIG GALAXY','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 21,'K-HOME','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 22,'AQUQRIUM','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 23,'LEREVE','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 24,'SHIZUKU','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 25,'FOOT PRINTER','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 26,'UKIUKI UTOPIA','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 27,'PIZZA SEIJIN','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 28,'CHOCO TIME','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 29,'CINEMA JAPAN','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 30,'KINNOSAWA','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 31,'RAKURAKU','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 32,'KURUYAMA','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 33,'MACKEY PARK','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 34,'SAKATIKE','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 35,'GEKIDAN ROADSHOW','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 36,'GPS COFFEE','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 37,'MIRA-MODE','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 38,'REWRITE','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 39,'SAMURAI','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 40,'INTERNOUSDEV','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 41,'NAGOMI','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 41,'NOEL','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 42,'LUSSO','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 43,'DEBUT','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 44,'NADESHIKO','http://www.internousdev.com/musical/','yasai1.jpg',2014),
( 45,'SHIKI','http://www.internousdev.com/musical/','yasai1.jpg',2014);